migrate to mandatory name usage

diff --git a/cmd/cmd_archive b/cmd/cmd_archive
--- a/cmd/cmd_archive
+++ b/cmd/cmd_archive
@@ -1,6 +1,8 @@
 #!/bin/bash
-echo "Archive appID=$appID"
-if [ "$hint" != "" ]; then
-        echo "Optional hint = $hint"
+appID=$(getAppID "$name")
+if [ "$appID" = "" ]; then
+    echo "app not found"
+    exit 1
 fi
+echo "Archive appID=$appID ($hint)"
 execute archive $appID "$hint"
diff --git a/cmd/cmd_ssh b/cmd/cmd_ssh
--- a/cmd/cmd_ssh
+++ b/cmd/cmd_ssh
@@ -1,2 +1,8 @@
 #!/bin/bash
+appID=$(getAppID "$name")
+if [ "$appID" = "" ]; then
+    echo "app not found"
+    exit 1
+fi
+port="$(execute getport $appID)"
 ssh -p $port app@$host
