add option to connect app to web

diff --git a/install/bin/create_app_container b/install/bin/create_app_container
--- a/install/bin/create_app_container
+++ b/install/bin/create_app_container
@@ -23,7 +23,17 @@ else
     intport="$1"
 fi
 shift
-guestmount="$1"
+if [ "$1" = "none" ]; then
+    guestmount=""
+else
+    guestmount="$1"
+fi
+shift
+if [ "$1" = "none" ]; then
+    webspec=""
+else
+    webspec="$1"
+fi
 appdir=$(cat - << END
 #name__mac_______________vent___vnet_ip_______guest_ip________ssh_forward
 APPTS_APP_DIRECTORY
@@ -63,6 +73,26 @@ sshforw=$(echo $nextfree | awk '{print $6}')
 #echo "router  = $router"
 #echo "guestip = $guestip"
 #echo "sshforw = $sshforw"
+
+if [ "$webspec" != "" ]; then
+    URIredir=$(echo "$webspec" | awk -F ',' '{print $1}')
+    servPort=$(echo "$webspec" | awk -F ',' '{print $2}')
+    URIdesti=$(echo "$webspec" | awk -F ',' '{print $3}')
+    IPredir=$guestip
+    if [ "$URIredir" = "" ]; then
+        echo "Error - need redirection URI"
+        exit 1
+    fi
+    if [ "$servPort" != "" ]; then
+        servPort=":$servPort"
+    fi
+    if [ "$URIdesti" != "" ]; then
+        URIdesti="${URIdesti}/"
+    fi
+    echo "Web-Access URI=$URIredir DEST_IP=$IPredir DEST_PORT=$servPort DEST_URI=$URIdesti"
+    mkdir -p /etc/nginx/appts
+    echo "location /${URIredir}/ {proxy_pass http://${IPredir}${servPort}/$URIdesti;}" > /etc/nginx/appts/$desc.location
+fi
 
 if [ "$guestmount" != "" ]; then
     echo "Guest-mount: $guestmount"
diff --git a/install/bin/delete_app_container b/install/bin/delete_app_container
--- a/install/bin/delete_app_container
+++ b/install/bin/delete_app_container
@@ -9,20 +9,28 @@
 # License: GPLv3
 ###############################################################################
 
-
-name="$1"
+appID="$1"
 
 cd /var/lib/lxc
 
-if [ ! -d "$name" ]; then
-	echo "App $name does not exist"
-	exit 1
+if [ ! -d "$appID" ]; then
+        echo "App $appID does not exist"
+        exit 1
 fi
 
-if [ ! -e $name/is_appts ]; then
-	echo "App $name cannot be deleted"
-	exit 1
+if [ ! -e $appID/is_appts ]; then
+        echo "App $appID cannot be deleted"
+        exit 1
 fi
 
-lxc-destroy -f -n $name
+name="$(cat $appID/appts.name)"
+lxc-destroy -f -n $appID
 bin/fw-setup > /dev/null
+
+web=/etc/nginx/appts/$name.location
+if [ -e "$web" ]; then
+    echo "Disable Web"
+    rm -f "$web"
+    service nginx reload
+fi
+
